Improve the error message for missing input file
Without this, we get an opaque error such as:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/ramnivas/open-source/payas/payas-parser/src/parser/mod.rs:13:58
```

After the change, we get a nicer message:
```
Error: File 'integration-tests/interceptor/concert.clayx' not found
```