Consider the --allow-destructive-changes flag
When applying changes to the database, we had ignored the
--allow-destructive-changes flag.

```
> exo schema migrate --allow-destructive-changes --apply-to-database
Error: Migration contains destructive changes
```

This commit removes the check in the migrate command and passes
the flag along to the `Migration::apply` method, which correctly uses it.

Fixes #1479