Show a better error message when the server fails to start (#486)
Earlier, if, for example, user didn't set CLAY_DATABAE_URL, 'clay serve'
would fail with an error message along with a Rust stack trace.
```
$ clay serve
Watching: "/Users/ramnivas/open-source/claytip-docs/sample-code/todo-app"
thread 'main' panicked at 'Failed to access database: CLAY_DATABASE_URL must be provided

Caused by:
    environment variable not found', payas-server-core/src/lib.rs:54:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This change handles errors in place of `unwrap()`ing them and shows
a better error message:
```
$ clay serve
Watching: "/Users/ramnivas/open-source/claytip-docs/sample-code/todo-app"
Configuration error: Env CLAY_DATABASE_URL must be provided
```